version: "3"
services:

  webgrind:
    image: edisga/webgrind:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      # Replace '/path/to/xdebug/files' with the actual path of the xDebug profiling files
      - /path/to/xdebug/files:/tmp
